feat: add GitHub Actions workflow for CI/CD with build, test, lint, and Docker image push steps.

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -42,12 +42,32 @@ jobs:
 
   push:
     runs-on: ubuntu-latest
-
     needs: build
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+    
+      - name: Verify Secrets Access
+        run: |
+          echo "----------------------------------------------------"
+          echo "Debugging Secrets..."
+          echo "Username being used: '${{ secrets.DOCKERHUB_USERNAME }}'"
+          
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "❌ ERROR: DOCKERHUB_USERNAME is empty/undefined."
+            exit 1
+          fi
+
+          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+            echo "❌ ERROR: DOCKERHUB_TOKEN is empty/undefined."
+            exit 1
+          else
+            echo "✅ DOCKERHUB_TOKEN is present (masked)."
+          fi
+          echo "----------------------------------------------------"
+      
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
@@ -65,29 +85,3 @@ jobs:
           file: ./Dockerfile
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}
-
-  update-newtag-in-helm-chart:
-    runs-on: ubuntu-latest
-
-    permissions:
-      contents: write
-
-    needs: push
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.TOKEN }}
-
-      - name: Update tag in Helm chart
-        run: |
-          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml
-
-      - name: Commit and push changes
-        run: |
-          git config --global user.email "judechihanachchu@gmail.com"
-          git config --global user.name "JudeCodeHub"
-          git add helm/go-web-app-chart/values.yaml
-          git commit -m "Update tag in Helm chart"
-          git push
